name: de-project

on:
  push:
    branches:
      - main

jobs:

  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13.1'
      - name: make requirements
        run: make requirements
      - name: make dev-setup
        run: make dev-setup
      # - name: make run-checks
      #   run: make run-checks

  deploy-lambda:
    name: deploy-lambda
    runs-on: ubuntu-latest
    needs: run-tests
    environment: dev
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    # install terraform
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        EMAIL: ${{ env.EMAIL}}
  
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform init
      working-directory: ./terraform
      run: terraform init
    # terraform plan
    - name: Terraform plan
      working-directory: ./terraform
      run: terraform plan
    # terraform fmt
    - name: Terraform format
      working-directory: ./terraform
      run: terraform fmt
    # terraform apply
    - name: Terraform apply 
      working-directory: ./terraform
      run: terraform apply -auto-approve